name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ato
          path: build/*
          retention-days: 1
  
  deploy-to-server:
    name: deploy the ato website frontend to static server
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ato

      - name: Send files to server
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.AWS_SERVER_HOST }}
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/ato/"
      
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: "ubuntu@${{ secrets.AWS_SERVER_HOST }}"
          privateKey: ${{ secrets.AWS_KEY }}
          debug: false
          command: |
            cd /home/ubuntu
            sudo rm -rf /var/www/html/frontend
            sudo mv ato /var/www/html/frontend
            sudo chmod -R 777 /var/www/html/frontend

      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: ato